### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by IzaZed** [UPBGE/uplogic#13]
- [x] Loop Nodes
- [x] Sound Nodes Start/Stop
- [ ] Re-Implement Save/Load
- [x] Spawn Pool rework
- [x] Expose input variables for node trees
- [x] Slider Widget doesn't follow when parent moves
- [ ] C++ Experiments
